services:
  db:
    image: postgres:16.3
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
  pgadmin:
    image: dpage/pgadmin4:8.4
    ports:
      - 8888:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: jakeh@me.com
      PGADMIN_DEFAULT_PASSWORD: secret
volumes:
  postgres:
  pgadmin:
